name: Upgrader

on:
  workflow_dispatch:
  schedule:
    - cron: "7 22 21 * *"

jobs:
  upgrade:
    uses: browniebroke/github-actions/.github/workflows/poetry-upgrade.yml@v1
    secrets:
      gh_pat: ${{ secrets.GITHUB_TOKEN }}
